### ISSUE TITLE
Add admission webhook validation for Path based on path type

### ISSUE THREAD

**Issue by hbagdi** [kubernetes-sigs/gateway-api#873] opened 2021-09-20 16:58 UTC
**What would you like to be added**:

Validate HTTPPathMatch.Value when Type is Exact or Prefix.
See upstream for inspiration: https://github.com/kubernetes/kubernetes/blob/f55101913fe7e5fbc6ae1aef5cc2f3a3e2300e03/pkg/apis/networking/validation/validation.go#L373
Do not validate for Regex since regex validation is really hard and the API is open to multiple regex engines.

**Why this is needed**:

To align with Ingress spec and for a better UX.

**Comment by ccfishk** [comment] 2021-10-03 23:13
Believe the issue is resolved as following
https://github.com/kubernetes-sigs/gateway-api/blob/master/pkg/util/utils_test.go#L79
https://github.com/kubernetes-sigs/gateway-api/blob/master/pkg/util/utils_test.go#L85

**Comment by robscott** [comment] 2021-11-15 22:19
This was fixed by https://github.com/kubernetes-sigs/gateway-api/pull/894.

**Closed by robscott** 2021-11-15 22:19 UTC
Labels: kind/feature
