### ISSUE TITLE
GEP: Add support for Route inclusion and delegation

### ISSUE THREAD

**Issue by Jeff-Apple** [kubernetes-sigs/gateway-api#1058] opened 2022-03-22 04:17 UTC
**What would you like to be added**:
Add support for a 2-tier hierarchy of route configuration to allow partial delegation of route settings and, provide more flexibility in how route configurations are organized and managed.

The formal GEP document will be based on the following document but with some changes based on the feedback and discussions that have taken place since it was last modified: [K8s Gateway API - Route inclusion and delegation](https://docs.google.com/document/d/1iumYQQMaB9y-PCtMsRwVfzKlZXZDejr_fO0krXn3F90) 

**Why this is needed**:
1.  The current model for delegation in Gateway API, has only one point where gateway owners can delegate some of the route configuration; where Routes attach to Listeners. This is basically an all or nothing model with very little flexibility. 

2.  Some scenarios need multiple RouteRules to have a subset of configuration settings that are the same in all of them (e.g., a specific RouteFilter config). The RouteRules might be in the same Route or many Routes. The only way to currently do that is to administratively add those settings to each RouteRule. This can result in much larger Route configurations and, frequently, configuration drift over time. 

**Additional Information**:
This issue is for tracking the progress of the PR containing the formal GEP document.

**Link to PR:** [https://github.com/kubernetes-sigs/gateway-api/pull/1085](https://github.com/kubernetes-sigs/gateway-api/pull/1085)

**Comment by shaneutt** [comment] 2023-03-08 21:04
Looks like this is effectively a duplicate of https://github.com/kubernetes-sigs/gateway-api/issues/1058 now. Closing as a duplicate, but if I've missed some context please ping me and/or re-open!

**Comment by shaneutt** [comment] 2023-03-08 21:07
Ultimately #1085 was auto-closed due to inactivity, so it would appear that for the moment we don't have anyone actively championing this effort and moving it forward. For now we'll consider it closed, but if anyone is interested in pushing for it please do feel free to ping here and we can re-open it any time.

**Closed by shaneutt** 2023-03-08 21:07 UTC
Labels: kind/feature, lifecycle/frozen

**Comment by youngnick** [comment] 2023-11-30 22:44
Yes, the current state is that this is basically abandoned, because it's very difficult to define how the inclusion should work while still using HTTPRoute as the object.

I should also note that past experience says this will be a _lot_ of work, so I think that interested folks should look at restarting with a fresh Github Discussion. But I think it's fair to say that this will require some pushing, as there are a number of other features currently higher on the priority list.

**Comment by EItanya** [comment] 2023-12-01 02:04
That's fair, is there a list of current prioritized items?

**Comment by shaneutt** [comment] 2023-12-01 15:56
I don't recall us leaving this with any sort of playbook about what to do next :thinking: 

My perspective: while I think there's plenty of prior art to consult here, I think the next step for you as someone interested would be to propose a "What" and "Why" in something like a GitHub discussion (and also put it on the meeting agendas to discuss periodically), basically as a _new_ effort that references the old one: let's try to determine with strong clarity **what** we want to do and **why** we want to do it, with no "_how_" we do it yet. I personally would particularly want to see **more user stories** that help to show the value to Gateway API end-users. Through that discussion process we should gather at least one (if not multiple) other implementers who need this and are in alignment on the what and why. If we can establish that, this might be good grounds for a re-open, or maybe more appropriately a new GEP inspired by the original work.

Does that make sense, and is that helpful to you?
