### ISSUE TITLE
TLSConfig.mode is "optional", but has no default

### ISSUE THREAD

**Issue by tommie** [kubernetes-sigs/gateway-api#2070] opened 2023-05-27 16:48 UTC
**What happened**:
Looking at https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.GatewayTLSConfig, the `mode` is optional, but it is not explained what it means if this is missing.

The `certificateRefs` field says:

> This field is required to have at least one element when the mode is set to “Terminate” (default) and is optional otherwise.

Which suggests that "terminate" is actually the default.

**What you expected to happen**:
It is clearly stated what happens if the field isn't present.

**Anything else we need to know?**:
Neither [Envoy Gateway](https://github.com/envoyproxy/gateway/blob/80db45944e010a5ba8eb2636201450ffb1a59f8e/internal/provider/kubernetes/helpers.go#L182) nor [cert-manager](https://github.com/cert-manager/cert-manager/blob/c5e6bf39d688d202592318eaf91988466a7ee37b/pkg/controller/certificate-shim/sync.go#L283) handle "terminate" as the default.

**Comment by shaneutt** [comment] 2023-05-30 16:28
We talked about this in our sync today, we need to do a little more thinking about what we wanna do next with this one, I'll triage it forward:

/assign @shaneutt

**Comment by shaneutt** [comment] 2023-05-30 20:03
Discussed this with the other maintainers, we definitely need some updates here.

/triage accepted
/milestone v1.0.0
/unassign

We need to start by documenting that the unset behavior is dependent on protocol.

/kind documentation
/help

**Comment by shaneutt** [comment] 2023-07-10 22:49
Talked about this one in the sync, looks like Terminate IS the default? https://github.com/kubernetes-sigs/gateway-api/blob/bf76bd0499cffa94966a218678bef86aac948943/apis/v1beta1/gateway_types.go#L310C35-L310C35

/assign @robscott

**Comment by robscott** [comment] 2023-10-05 23:50
Confirmed that Terminate is the default, closing this one out.

API:
https://github.com/kubernetes-sigs/gateway-api/blob/d4ff2d4f07ce47222a4f97296618dbb09b2538dd/apis/v1beta1/gateway_types.go#L352-L353

CRD:
https://github.com/kubernetes-sigs/gateway-api/blob/d4ff2d4f07ce47222a4f97296618dbb09b2538dd/config/crd/standard/gateway.networking.k8s.io_gateways.yaml#L445-L446

/close

**Closed by robscott** 2023-10-05 23:50 UTC
Labels: kind/bug, kind/documentation, triage/accepted, release-blocker

**Comment by tommie** [comment] 2023-10-06 06:23
Should I make a PR to add this to the docs?

This issue was about the docs not stating it. Other optional enum fields explain what missing means.

**Comment by robscott** [comment] 2023-10-06 17:42
@tommie yep, that makes sense, sorry for the confusion here!
