### ISSUE TITLE
Release 0.5.0 contains duplicate kind:Namespace/gateway-system object definition.

### ISSUE THREAD

**Issue by eigood** [kubernetes-sigs/gateway-api#1374] opened 2022-09-02 18:45 UTC
I'm attempting to reference either the standard-install.yaml or experimental-install.yaml on the releases page, via a kustomization.yaml/resources: tag.  However, both of those files contain a duplicate definition of the gateway-system namespace.  This breaks when applied directly via using via helmfile/helm/kustomize pipeline.

To work around this I downloaded the files and I modified them locally, to remove the duplicate Namespace.

**Comment by tokers** [comment] 2022-09-04 10:38
What do you mean by saying a duplicate definition of the `gateway-system`?  A re-defintion for Kubernetes namespace?

**Comment by robscott** [comment] 2022-09-06 00:38
It looks like the problem is that both `config/webhook/certificate_config.yaml` and `config/webhook/admission_webhook.yaml` include the namespace definition. We concatenate those files together here: https://github.com/kubernetes-sigs/gateway-api/blob/83eac3a978a473947db595c5a1dcc79a347dcf9e/hack/build-install-yaml.sh#L42-L58.

I don't think we're suggesting anyone use the individual YAML files, so it may make sense to pull out the namespace definition to a separate `0-namespace.yaml` file.

**Comment by gyohuangxin** [comment] 2022-09-06 02:05
@robscott I'm interesting in contributing to gateway-api project and I think this issue is a good start, can you assign it to me? Thanks.

**Comment by robscott** [comment] 2022-09-06 03:19
Thanks!

/assign @gyohuangxin

**Comment by gyohuangxin** [comment] 2022-09-06 03:22
@robscott Thanks, I just created a PR, can you review it?

**Comment by robscott** [comment] 2022-09-12 21:54
Opening this back up to track a cherry pick into release-0.5

**Comment by gyohuangxin** [comment] 2022-09-13 03:24
@robscott I raised a PR to cherry pick it into release-0.5, please review it, thanks.

**Comment by mikemorris** [comment] 2022-09-16 01:18
/close

Cherry pick to 0.5 in #1387 has merged.

**Closed by mikemorris** 2022-09-16 01:18 UTC
Labels: kind/bug, help wanted
