### ISSUE TITLE
Support fallback in HTTPRoute

### ISSUE THREAD

**Issue by hzxuzhonghu** [kubernetes-sigs/gateway-api#1818] opened 2023-03-15 09:31 UTC
**What would you like to be added**:

In springcloud, Feign provides fallback feature, when a calling to a service fails, then it can fall back to call another service.

It is common when the service is serving user's request, directly returning real failure reason sometimes is unacceptable. In this case, if the system can fall back to another service, which can handle kinds of such failure, it is very good for developers to handle it in every services

**Why this is needed**:

**Comment by shaneutt** [comment] 2023-03-15 14:33
@hzxuzhonghu it seems like this may be similar or even a duplicate of https://github.com/kubernetes-sigs/gateway-api/issues/1802, would you please give that one a read and let me know if it already covers the need you're trying to resolve here?

**Comment by hzxuzhonghu** [comment] 2023-03-15 15:05
Thanks, can be covered

**Comment by shaneutt** [comment] 2023-03-15 15:11
Closing as a duplicate of #1802, thanks @hzxuzhonghu :vulcan_salute:

**Closed by shaneutt** 2023-03-15 15:11 UTC
Labels: kind/feature, triage/needs-information
