### ISSUE TITLE
Conditions for BackendPolicy

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/gateway-api#590] opened 2021-03-19 20:51 UTC
Currently, BackendPolicy only has `ConditionNoSuchBackend` defined. There are other ways a backendpolicy may be invalid though:
* BackendRef is unknown/unsupported type
* Certificate ref is unknown/unsupported type, or does not exist

One other issue is that, unlike routes and gateways which all point back to a single controller eventually (via class), there is no controller association with BackendPolicy. How do we manage multiple controllers and BackendPolicy?

**Comment by robscott** [comment] 2021-03-19 21:17
Agree that these would be good conditions to add. Unfortunately the unknown/unsupported type conditions are going to be implementation specific (one implementation may support a type of backend that another does not). BackendPolicy is certainly one of our least refined resources at this point, and status is rather difficult to solve. 

The way we've currently defined it, BackendPolicy refers to backends. Controllers would check to see if a BackendPolicy applied to a backend they were processing, and the config in a BackendPolicy was intended to be entirely portable. When we added status here, the initial solution was for implementation-specific messages to be [added on the Route or Gateway level](https://github.com/kubernetes-sigs/gateway-api/blob/master/apis/v1alpha1/backendpolicy_types.go#L125-L127).

Unfortunately, there are a lot of different ways we could group these conditions, by backend, route, gateway, controller, or implementation. I think the best option might be to group conditions by GatewayClass. If an implementation is using a BackendPolicy for a given class, it would add conditions to status. This feels quite relevant to https://github.com/kubernetes-sigs/gateway-api/issues/591.

**Comment by hbagdi** [comment] 2021-07-26 20:11
@robscott Do you think reference policy needs these enhancement or should status conditions be part of the specific reference policies?
In my view, some common ground would be helpful.

**Comment by robscott** [comment] 2021-07-26 20:58
Thanks for following up on this @hbagdi! I've created #738 to track the equivalent of this going forward, and I think we can safely close this one now. Feel free to reopen if not.

/close

**Closed by robscott** 2021-07-26 20:59 UTC
Labels: kind/cleanup, lifecycle/rotten
