### ISSUE TITLE
Add support for HTTP rewrites

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#678] opened 2021-05-21 18:30 UTC
**What would you like to be added**:
In addition to support for redirects (https://github.com/kubernetes-sigs/gateway-api/issues/200), it would be useful to extend HTTPRoute to support rewrites before forwarding traffic.

**Why is this needed**:
As a simple example, requests to `customer1/store` and `customer2/store` may require different routing while still being forwarded to backends as requests to `/store`.

**Comment by robscott** [comment] 2021-08-19 19:12
This will be covered by GEP https://github.com/kubernetes-sigs/gateway-api/issues/726.

/lifecycle frozen

**Comment by shaneutt** [comment] 2022-08-05 14:07
This is being closed as duplicate of https://github.com/kubernetes-sigs/gateway-api/issues/726, the work will continue in that issue.

**Closed by shaneutt** 2022-08-05 14:07 UTC
Labels: kind/feature, lifecycle/frozen
